/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.sistemaCondominio.telas;
import java.sql.*;
import javax.swing.JOptionPane;
import br.com.sistemaCondominio.dal.ModuloConexao;

/**
 *
 * @author laris
 */
public class CadastroResidencia extends javax.swing.JInternalFrame {
     private Connection conexao = null;
    /**
     * Creates new form CadastroResidencia
     */
    public CadastroResidencia() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroResidencia = new javax.swing.JTextField();
        txtAreaResidencia = new javax.swing.JTextField();
        txtProprietarioResidencia = new javax.swing.JTextField();
        txtTelefoneResidencia = new javax.swing.JTextField();
        btnSalvaResidencia = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRuaResidencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIdProprietario = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Residencia");
        setPreferredSize(new java.awt.Dimension(910, 540));

        jLabel1.setText("*Campo Obrigatório");

        jLabel2.setText("*Área: (m²)");

        jLabel3.setText("*Proprietário:");

        jLabel4.setText("*Telefone:");

        txtNumeroResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroResidenciaActionPerformed(evt);
            }
        });

        btnSalvaResidencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalvaResidencia.setText("Salvar");
        btnSalvaResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaResidenciaActionPerformed(evt);
            }
        });

        jLabel5.setText("*Número:");

        jLabel6.setText("*Rua:");

        jLabel7.setText("*ID proprietário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnSalvaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(188, 188, 188)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProprietarioResidencia, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                                .addComponent(txtAreaResidencia)
                                .addComponent(txtRuaResidencia)
                                .addComponent(txtNumeroResidencia)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(180, 180, 180)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4)
                                    .addGap(35, 35, 35)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIdProprietario, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                .addComponent(txtTelefoneResidencia)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRuaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAreaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProprietarioResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefoneResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnSalvaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        setBounds(0, 0, 910, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroResidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroResidenciaActionPerformed
    private void limparCampos() {
        txtNumeroResidencia.setText(null);
        txtRuaResidencia.setText(null);
        txtAreaResidencia.setText(null);
        txtProprietarioResidencia.setText(null);
        txtIdProprietario.setText(null);
        txtTelefoneResidencia.setText(null);
    }
    private void btnSalvaResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaResidenciaActionPerformed
        // validação dos campos obrigatórios:
        if (txtNumeroResidencia.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o número da residência.");
            txtNumeroResidencia.requestFocus();
            return;
        }
        if (txtRuaResidencia.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha a rua da residência.");
            txtRuaResidencia.requestFocus();
            return;
        }
        if (txtAreaResidencia.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o tamanho da residência.");
            txtAreaResidencia.requestFocus();
            return;
        }
        if (txtProprietarioResidencia.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o nome do proprietário.");
            txtProprietarioResidencia.requestFocus();
            return;
        }
        if (txtIdProprietario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o ID do proprietário.");
            txtIdProprietario.requestFocus();
            return;
        } 
        if (txtTelefoneResidencia.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o telefone do proprietário.");
            txtTelefoneResidencia.requestFocus();
            return;
        }
        // verifica se foi inserido um numero no campo area
            try{
                
               String area_txt = txtAreaResidencia.getText().trim();
               area_txt = area_txt.replace(",", ".");
              float area_residencia = Float.parseFloat(area_txt);
              if(area_residencia <= 0){
                  JOptionPane.showMessageDialog(this, 
                "A área deve ser maior que zero.Por favor, coloque outro valor",
                "Valor inválido", JOptionPane.WARNING_MESSAGE);
                 txtAreaResidencia.setText(""); 
                 txtAreaResidencia.requestFocus();
                  return;
              }
            }
             catch (NumberFormatException ex){
                 JOptionPane.showMessageDialog(this, 
                "Área inválida! Digite apenas números.",
                "Erro de Formato", JOptionPane.ERROR_MESSAGE);
                txtAreaResidencia.setText(""); 
                txtAreaResidencia.requestFocus();
             }
        // verifica se o id do proprietario é válido
        try{
            String sqlVerifica = "SELECT COUNT(*) FROM usuario WHERE id_usuario = ?";
            int id_proprietario = Integer.parseInt(txtIdProprietario.getText().trim());
            PreparedStatement pstVerifica = conexao.prepareStatement(sqlVerifica);
            pstVerifica.setInt(1, id_proprietario);
            ResultSet rs = pstVerifica.executeQuery();
            if (rs.next() && rs.getInt(1) == 0) {
                JOptionPane.showMessageDialog(this, 
                "Não existem moradores cadastrados com esse ID. Por favor, coloque outro.",
                "ID inválido", JOptionPane.WARNING_MESSAGE);
            rs.close();
            pstVerifica.close();
            return;
            }
            rs.close();
            pstVerifica.close();
        }
        catch (NumberFormatException ex) {
    
            JOptionPane.showMessageDialog(this, 
            "ID inválido! Digite apenas números.",
            "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            txtIdProprietario.setText(""); 
            txtIdProprietario.requestFocus();
        } 
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, 
                "Erro ao verificar ID do proprietário: " + e.getMessage(),
                "Erro de Banco", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // salva cadastro no banco
        try{
            String sqlResidencia = "INSERT INTO residencia (numero, rua, nome_proprietario, id_proprietario, area, telefone) VALUES (?,?,?,?,?,?)";
            Integer idResidencia = null;
            PreparedStatement pstResidencia = conexao.prepareStatement(sqlResidencia, Statement.RETURN_GENERATED_KEYS);
            pstResidencia.setString(1, txtNumeroResidencia.getText().trim());
            pstResidencia.setString(2, txtRuaResidencia.getText().trim());
            pstResidencia.setString(3, txtProprietarioResidencia.getText().trim());
            pstResidencia.setInt(4,Integer.parseInt(txtIdProprietario.getText().trim()));
            pstResidencia.setFloat(5,  Float.parseFloat(txtAreaResidencia.getText().trim()));
            pstResidencia.setString(6, txtTelefoneResidencia.getText().trim());
            
            int resultado = pstResidencia.executeUpdate();
            if (resultado>0){
                ResultSet rsKeys = pstResidencia.getGeneratedKeys();
                if (rsKeys.next()) {
                    // Tenta obter pelo nome da coluna primeiro, depois pelo índice
                    try {
                        idResidencia = rsKeys.getInt("id_usuario");
                    } catch (SQLException e) {
                        // Se não encontrar pelo nome, tenta pelo índice
                        idResidencia = rsKeys.getInt(1);
                    }
                }
                rsKeys.close();
            }
             pstResidencia.close();
            
            if (idResidencia == null) {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar Residência. Tente novamente.");
                return;
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar residência: " + e.getMessage());
            return;
        }
        //Todas as informações foram salvas na tabela residencia
        JOptionPane.showMessageDialog(this, 
            "Residencia cadastrado com sucesso!\n" +
            "Numero: " + txtNumeroResidencia.getText().trim() + "\n" +
            "Rua: " + txtRuaResidencia.getText().trim() + "\n" +
            "Proprietario: " + txtProprietarioResidencia.getText().trim(),
            "Cadastro Realizado", JOptionPane.INFORMATION_MESSAGE);
        
        // Limpa os campos
        limparCampos();
    }//GEN-LAST:event_btnSalvaResidenciaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvaResidencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAreaResidencia;
    private javax.swing.JTextField txtIdProprietario;
    private javax.swing.JTextField txtNumeroResidencia;
    private javax.swing.JTextField txtProprietarioResidencia;
    private javax.swing.JTextField txtRuaResidencia;
    private javax.swing.JTextField txtTelefoneResidencia;
    // End of variables declaration//GEN-END:variables
}
