/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.sistemaCondominio.telas;

import java.sql.*;
import javax.swing.JOptionPane;
import br.com.sistemaCondominio.dal.ModuloConexao;

/**
 *
 * @author laris
 */
public class CadastroMoradores extends javax.swing.JInternalFrame {

    private Connection conexao = null;

    /**
     * Creates new form CadastroMoradores
     */
    public CadastroMoradores() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeMorador = new javax.swing.JTextField();
        txtCpfMorador = new javax.swing.JTextField();
        txtTelefoneMorador = new javax.swing.JTextField();
        txtPlacaVeiculo = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbbVeiculo = new javax.swing.JComboBox<>();
        btnSalvaResidencia = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        cbbPerfil = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CadastroMoradores");
        setMinimumSize(new java.awt.Dimension(910, 540));
        setPreferredSize(new java.awt.Dimension(910, 540));

        jLabel1.setText("*Nome");

        jLabel2.setText("*CPF:");

        jLabel3.setText("Tipo de veículo:");

        jLabel4.setText("*Telefone:");

        jLabel5.setText("Placa:");

        jLabel6.setText("*Rua:");

        jLabel7.setText("*Campo Obrigatório");

        jLabel8.setText("*Numero");

        cbbVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Carro", "Moto", "Caminhão", "Outro" }));
        cbbVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbVeiculoActionPerformed(evt);
            }
        });

        btnSalvaResidencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalvaResidencia.setText("Salvar");
        btnSalvaResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaResidenciaActionPerformed(evt);
            }
        });

        jLabel9.setText("*Login:");

        jLabel10.setText("*Senha:");

        jLabel11.setText("*Perfil:");

        cbbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Administrador", "Morador" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(705, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCpfMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(581, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefoneMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnSalvaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtNomeMorador, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(cbbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel5))
                                                        .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(27, 27, 27)
                                                            .addComponent(jLabel8)
                                                            .addGap(27, 27, 27)
                                                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(18, 18, 18)
                                                            .addComponent(txtPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGap(29, 29, 29))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(41, 41, 41)
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 149, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeMorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCpfMorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefoneMorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvaResidencia)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        setBounds(0, 0, 910, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbVeiculoActionPerformed

    private void btnSalvaResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaResidenciaActionPerformed
        // Validação dos campos obrigatórios
        if (txtNomeMorador.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o nome do morador.");
            txtNomeMorador.requestFocus();
            return;
        }
        
        if (txtCpfMorador.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o CPF do morador.");
            txtCpfMorador.requestFocus();
            return;
        }
        
        if (txtTelefoneMorador.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o telefone do morador.");
            txtTelefoneMorador.requestFocus();
            return;
        }
        
        if (txtRua.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha a rua.");
            txtRua.requestFocus();
            return;
        }
        
        if (txtNumero.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o número.");
            txtNumero.requestFocus();
            return;
        }
        
        if (txtLogin.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o login.");
            txtLogin.requestFocus();
            return;
        }
        
        if (txtSenha.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha a senha.");
            txtSenha.requestFocus();
            return;
        }
        
        String username = txtLogin.getText().trim();
        
        // Verifica se o username já existe
        String sqlVerifica = "SELECT COUNT(*) FROM usuario WHERE username = ?";
        try {
            PreparedStatement pstVerifica = conexao.prepareStatement(sqlVerifica);
            pstVerifica.setString(1, username);
            ResultSet rs = pstVerifica.executeQuery();
            
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(this, 
                    "Este login já está em uso. Por favor, escolha outro.",
                    "Login Duplicado", JOptionPane.WARNING_MESSAGE);
                rs.close();
                pstVerifica.close();
                return;
            }
            rs.close();
            pstVerifica.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao verificar login: " + e.getMessage());
            return;
        }
        
        // Validação do perfil
        String perfilSelecionado = (String) cbbPerfil.getSelectedItem();
        if (perfilSelecionado == null || perfilSelecionado.trim().isEmpty() || perfilSelecionado.equals(" ")) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um perfil.");
            cbbPerfil.requestFocus();
            return;
        }
        
        // Insere o usuário na tabela usuario (incluindo todos os campos obrigatórios)
        String sqlUsuario = "INSERT INTO usuario (nome, cpf, telefone, rua, numero, veiculo, placa, username, senha, perfil) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        Integer idUsuario = null;
        
        try {
            PreparedStatement pstUsuario = conexao.prepareStatement(sqlUsuario, Statement.RETURN_GENERATED_KEYS);
            pstUsuario.setString(1, txtNomeMorador.getText().trim());
            pstUsuario.setString(2, txtCpfMorador.getText().trim());
            pstUsuario.setString(3, txtTelefoneMorador.getText().trim());
            pstUsuario.setString(4, txtRua.getText().trim());
            pstUsuario.setString(5, txtNumero.getText().trim());
            
            // Veículo - pode ser null se não selecionado
            String tipoVeiculo = (String) cbbVeiculo.getSelectedItem();
            if (tipoVeiculo == null || tipoVeiculo.trim().isEmpty() || tipoVeiculo.equals("  ")) {
                pstUsuario.setString(6, null);
            } else {
                pstUsuario.setString(6, tipoVeiculo);
            }
            
            // Placa - pode ser null se vazio
            String placa = txtPlacaVeiculo.getText().trim();
            if (placa.isEmpty()) {
                pstUsuario.setString(7, null);
            } else {
                pstUsuario.setString(7, placa);
            }
            
            pstUsuario.setString(8, username);
            pstUsuario.setString(9, new String(txtSenha.getPassword()));
            pstUsuario.setString(10, perfilSelecionado);
            
            int resultado = pstUsuario.executeUpdate();
            
            if (resultado > 0) {
                // Obtém o ID gerado
                ResultSet rsKeys = pstUsuario.getGeneratedKeys();
                if (rsKeys.next()) {
                    // Tenta obter pelo nome da coluna primeiro, depois pelo índice
                    try {
                        idUsuario = rsKeys.getInt("id_usuario");
                    } catch (SQLException e) {
                        // Se não encontrar pelo nome, tenta pelo índice
                        idUsuario = rsKeys.getInt(1);
                    }
                }
                rsKeys.close();
            }
            pstUsuario.close();
            
            if (idUsuario == null) {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário. Tente novamente.");
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário: " + e.getMessage());
            return;
        }
        
        // Todas as informações foram salvas na tabela usuario
        JOptionPane.showMessageDialog(this, 
            "Morador cadastrado com sucesso!\n" +
            "Nome: " + txtNomeMorador.getText().trim() + "\n" +
            "Login: " + username + "\n" +
            "Perfil: " + perfilSelecionado,
            "Cadastro Realizado", JOptionPane.INFORMATION_MESSAGE);
        
        // Limpa os campos
        limparCampos();
    }//GEN-LAST:event_btnSalvaResidenciaActionPerformed
    
    private void limparCampos() {
        txtNomeMorador.setText("");
        txtCpfMorador.setText("");
        txtTelefoneMorador.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtPlacaVeiculo.setText("");
        txtLogin.setText("");
        txtSenha.setText("");
        cbbVeiculo.setSelectedIndex(0);
        cbbPerfil.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvaResidencia;
    private javax.swing.JComboBox<String> cbbPerfil;
    private javax.swing.JComboBox<String> cbbVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCpfMorador;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNomeMorador;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPlacaVeiculo;
    private javax.swing.JTextField txtRua;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefoneMorador;
    // End of variables declaration//GEN-END:variables
}
