/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistemaCondominio.telas;

import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author laris
 */
public class ReservasAreasComuns extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReservasAreasComuns
     */
    public ReservasAreasComuns() {
        initComponents();
        populateDateAndTimeComponents();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservarActionPerformed(evt);
            }
        });
    }

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {
        String selectedArea = (String) jComboBoxArea.getSelectedItem();
        String selectedDay = (String) jComboBoxDay.getSelectedItem();
        String selectedMonth = (String) jComboBoxMonth.getSelectedItem();
        String selectedYear = (String) jComboBoxYear.getSelectedItem();
        Integer selectedHour = (Integer) jSpinnerHour.getValue();
        Integer selectedMinute = (Integer) jSpinnerMinute.getValue();

        if (selectedArea == null || selectedArea.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma área comum.");
            return;
        }

        // Basic date validation (e.g., check for valid day for month)
        // This can be more robust, but for now, a simple check.
        try {
            java.time.LocalDate.of(Integer.parseInt(selectedYear), Integer.parseInt(selectedMonth), Integer.parseInt(selectedDay));
        } catch (java.time.DateTimeException e) {
            JOptionPane.showMessageDialog(this, "Data selecionada inválida. Por favor, verifique o dia, mês e ano.");
            return;
        }

        String reservationDateTime = String.format("Área: %s, Data: %s/%s/%s, Hora: %02d:%02d",
                selectedArea, selectedDay, selectedMonth, selectedYear, selectedHour, selectedMinute);

        JOptionPane.showMessageDialog(this, "Reserva para: " + reservationDateTime + " (Funcionalidade de DB em desenvolvimento)");

        // TODO: Implement database interaction for checking availability and saving reservation
        // TODO: Implement notification to administrator
        // TODO: Update jTableReservas with new reservation
    }

    private void populateDateAndTimeComponents() {
        // Populate Area ComboBox
        jComboBoxArea.addItem("Piscina");
        jComboBoxArea.addItem("Churrascaria");
        jComboBoxArea.addItem("Sala de Festas");

        // Populate Day ComboBox
        for (int i = 1; i <= 31; i++) {
            jComboBoxDay.addItem(String.format("%02d", i));
        }

        // Populate Month ComboBox
        for (int i = 1; i <= 12; i++) {
            jComboBoxMonth.addItem(String.format("%02d", i));
        }

        // Populate Year ComboBox (e.g., current year +/- 5 years)
        int currentYear = java.time.Year.now().getValue();
        for (int i = currentYear - 5; i <= currentYear + 5; i++) {
            jComboBoxYear.addItem(String.valueOf(i));
        }

        // Configure Hour Spinner
        SpinnerModel hourModel = new SpinnerNumberModel(8, 0, 23, 1); // Default 8, min 0, max 23, step 1
        jSpinnerHour.setModel(hourModel);
        JSpinner.NumberEditor hourEditor = new JSpinner.NumberEditor(jSpinnerHour, "00");
        jSpinnerHour.setEditor(hourEditor);

        // Configure Minute Spinner
        SpinnerModel minuteModel = new SpinnerNumberModel(0, 0, 59, 15); // Default 0, min 0, max 59, step 15
        jSpinnerMinute.setModel(minuteModel);
        JSpinner.NumberEditor minuteEditor = new JSpinner.NumberEditor(jSpinnerMinute, "00");
        jSpinnerMinute.setEditor(minuteEditor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxArea = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDay = new javax.swing.JComboBox<>();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerHour = new javax.swing.JSpinner();
        jSpinnerMinute = new javax.swing.JSpinner();
        jButtonReservar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReservas = new javax.swing.JTable();



        jLabel1.setText("Área Comum:");

        jLabel2.setText("Data:");

        jLabel3.setText("Hora:");

        jButtonReservar.setText("Reservar");

        jScrollPane1.setViewportView(jTableReservas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerHour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonReservar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonReservar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JComboBox<String> jComboBoxArea;
    private javax.swing.JComboBox<String> jComboBoxDay;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerHour;
    private javax.swing.JSpinner jSpinnerMinute;
    private javax.swing.JTable jTableReservas;
    // End of variables declaration//GEN-END:variables
}
