/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistemaCondominio.telas;

import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author laris
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuMoradores = new javax.swing.JMenu();
        cadastraCliente = new javax.swing.JMenuItem();
        editarMoradores = new javax.swing.JMenuItem();
        menuResidencias = new javax.swing.JMenu();
        cadastrarResidencia = new javax.swing.JMenuItem();
        editarResidencia = new javax.swing.JMenuItem();
        menuReserva = new javax.swing.JMenu();
        menuTaxas = new javax.swing.JMenu();
        menumanutencao = new javax.swing.JMenu();
        menurelatorio = new javax.swing.JMenu();
        menuComunicacao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de condominio");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario.setText("Usuario");

        lbldata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbldata.setText("data");

        menuMoradores.setText("Moradores");

        cadastraCliente.setText("Cadastrar");
        menuMoradores.add(cadastraCliente);

        editarMoradores.setText("Editar/Excluir");
        editarMoradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMoradoresActionPerformed(evt);
            }
        });
        menuMoradores.add(editarMoradores);

        menu.add(menuMoradores);

        menuResidencias.setText("Residências");

        cadastrarResidencia.setText("Cadastrar");
        menuResidencias.add(cadastrarResidencia);

        editarResidencia.setText("Editar/Excluir");
        menuResidencias.add(editarResidencia);

        menu.add(menuResidencias);

        menuReserva.setText("Reserva de áreas");

        reservarArea = new javax.swing.JMenuItem();
        reservarArea.setText("Reservar");
        reservarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarAreaActionPerformed(evt);
            }
        });
        menuReserva.add(reservarArea);

        menu.add(menuReserva);

        menuTaxas.setText("Taxas");
        menu.add(menuTaxas);

        menumanutencao.setText("Manutenções");

        gerenciarManutencoes = new javax.swing.JMenuItem();
        gerenciarManutencoes.setText("Gerenciar Manutenções");
        gerenciarManutencoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarManutencoesActionPerformed(evt);
            }
        });
        menumanutencao.add(gerenciarManutencoes);

        menu.add(menumanutencao);

        menurelatorio.setText("Relatórios");

        gerarRelatorio = new javax.swing.JMenuItem();
        gerarRelatorio.setText("Gerar Relatório");
        gerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelatorioActionPerformed(evt);
            }
        });
        menurelatorio.add(gerarRelatorio);

        menu.add(menurelatorio);

        menuAcesso = new javax.swing.JMenu();
        menuAcesso.setText("Acesso");

        controleAcesso = new javax.swing.JMenuItem();
        controleAcesso.setText("Controle de Acesso");
        controleAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controleAcessoActionPerformed(evt);
            }
        });
        menuAcesso.add(controleAcesso);

        menu.add(menuAcesso);

        menuComunicacao.setText("Comunicações");
        menu.add(menuComunicacao);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldata)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1173, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editarMoradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMoradoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarMoradoresActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // mostra data atual do sistema ao inicializar a tela
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lbldata.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void reservarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarAreaActionPerformed
        // TODO add your handling code here:
        ReservasAreasComuns reservas = new ReservasAreasComuns();
        Desktop.add(reservas);
        reservas.setVisible(true);
        try {
            reservas.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            logger.log(java.util.logging.Level.WARNING, "Não foi possível maximizar a tela de reservas", e);
        }
    }//GEN-LAST:event_reservarAreaActionPerformed

    private void gerenciarManutencoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarManutencoesActionPerformed
        ManutencoesAreasComuns manutencoes = new ManutencoesAreasComuns();
        Desktop.add(manutencoes);
        manutencoes.setVisible(true);
        try {
            manutencoes.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            logger.log(java.util.logging.Level.WARNING, "Não foi possível maximizar a tela de manutenções", e);
        }
    }//GEN-LAST:event_gerenciarManutencoesActionPerformed

    private void gerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {
        TelaRelatorios relatorios = new TelaRelatorios();
        Desktop.add(relatorios);
        relatorios.setVisible(true);
        try {
            relatorios.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            logger.log(java.util.logging.Level.WARNING, "Não foi possível maximizar a tela de relatórios", e);
        }
    }

    private void controleAcessoActionPerformed(java.awt.event.ActionEvent evt) {
        TelaControleAcesso acesso = new TelaControleAcesso();
        Desktop.add(acesso);
        acesso.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem cadastraCliente;
    private javax.swing.JMenuItem cadastrarResidencia;
    private javax.swing.JMenuItem editarMoradores;
    private javax.swing.JMenuItem editarResidencia;
    private javax.swing.JMenuItem gerarRelatorio;
    private javax.swing.JMenuItem controleAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lbldata;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAcesso;
    private javax.swing.JMenu menuComunicacao;
    private javax.swing.JMenu menuMoradores;
    private javax.swing.JMenu menuReserva;
    private javax.swing.JMenu menuResidencias;
    private javax.swing.JMenu menuTaxas;
    private javax.swing.JMenu menumanutencao;
    private javax.swing.JMenu menurelatorio;
    private javax.swing.JMenuItem reservarArea;
    private javax.swing.JMenuItem gerenciarManutencoes;
    // End of variables declaration//GEN-END:variables
}
